### ISSUE TITLE
插件启用后于 b 站评论区选中文本困难

### ISSUE THREAD

**Issue by Y0ungSea** [scriptscat/scriptcat#352]
操作系统：Windows 11
浏览器：ZenBrowser 1.8.2b (基于 Firefox 135.0.1) (64 位)
ScriptCat：0.16.6

问题描述：
在浏览器中启用 ScriptCat 插件后，在哔哩哔哩视频网中选中文本时，发现选中困难。
我最初认为是我安装的脚本导致的。但即使关闭加载脚本，依然出现该情况。

我录制了 Gif 来说明情况。正常情况如下：

![Image](https://github.com/user-attachments/assets/19c6ba47-e020-4081-810f-243a4d310006)

然后这个是开启插件后的行为（拖动选中时我并未抬起鼠标）：

![Image](https://github.com/user-attachments/assets/3c8c841f-78f1-4eb1-aeed-f91ca9225a85)

另外，经测试，Tampermonkey 并不会出现这个情况。望修复。

**Comment by CodFrm** [comment]
Edge好像没遇到这个问题，是只有`ZenBrowser`有这个问题么？另外尝试关闭这个开关可以复现么？

![Image](https://github.com/user-attachments/assets/f39e7faf-d2ea-4948-ab34-bd91adb2ec7c)

**Comment by Y0ungSea** [comment]
> Edge好像没遇到这个问题，是只有`ZenBrowser`有这个问题么？另外尝试关闭这个开关可以复现么？
> 
> ![Image](https://github.com/user-attachments/assets/f39e7faf-d2ea-4948-ab34-bd91adb2ec7c)

我测试时已经关闭了这个开关，所以是的，关闭开关后问题依然存在。另外，还发现 Firefox 原版（我使用 winget 安装最新 Firefox）也有这个情况，似乎可以认为是 Firefox 系浏览器的通病。

**Comment by Y0ungSea** [comment]
@CodFrm 定位到问题了吗

**Comment by CodFrm** [comment]
使用Firefox 125版本没有出现，使用Firefox 136确实复现了上述问题，还没定位到

Firefox 139.0.4依旧存在

**Comment by Y0ungSea** [comment]
经过本编程菜鸟的实践，发现一个临时的解决方法，极大改善情况，提供给同样遇到问题的人。

在你的 userContent.css 加入以下代码：
```css
/* 修复 ScriptCat 启用时于 b 站评论区选中文本异常 */
@-moz-document domain("bilibili.com") {
  bili-rich-text {
    /* 该项原本值为 inline */
    --bili-rich-text-display: block !important;
  }
}
```

@CodFrm 这个起修复作用的css覆写了"bili-rich-text"元素的变量"--bili-rich-text-display"，变量原本值为"inline"，这是否对定位问题有所帮助？
